use_frameworks!
platform :ios, '9.3'

target 'dtacComponent_Example' do
  pod 'dtacComponent', :path => '../'

  target 'dtacComponent_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
